[workspace]
members = [
    "crates/mcp-server",
    "crates/common",
    "crates/index",
    "crates/context",
    "crates/tools",
    "crates/godot",
]
resolver = "2"

# Workspace license mirrors repository license
# Individual crates declare `license = "MIT"`.

#EOF