[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1"
tracing = "0.1"
walkdir = "2"

common = { path = "../common" }

[dev-dependencies]
tempfile = "3"
