name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --workspace --all-targets --locked

      - name: Test
        run: cargo test --workspace --all-targets --locked

      - name: Autodoc check (non-blocking)
        run: cargo run --locked -p tools --bin autodoc -- --check --json --root .
        continue-on-error: true

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run metatagger (non-blocking) and save JSON
        run: |
          cargo run --locked -p tools --bin metatagger -- --json --root . > metatagger-report.json || true
        continue-on-error: true

      - name: Upload metatagger report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: metatagger-report
          path: metatagger-report.json

      - name: Run godot analyzer (non-blocking) incl. scene validation and save JSON + SARIF
        run: |
          cargo run --locked -p godot --bin godot-analyzer -- --json --root . --validate-scenes --lint-gd --scene-json-out scene-findings.json > godot-analyzer-report.json || true
          cargo run --locked -p godot --bin godot-analyzer -- --root . --validate-scenes --lint-gd --sarif-out godot-analyzer.sarif || true
        continue-on-error: true

      - name: Upload godot analyzer reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: godot-analyzer-reports
          path: |
            godot-analyzer-report.json
            godot-analyzer.sarif
            scene-findings.json

      - name: Upload SARIF to GitHub Code Scanning (optional)
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: godot-analyzer.sarif
